networks:
  network_application:
    driver: bridge
volumes:
  volume_application:
  volume_postgres:
services:
  application:
    build:
      context: .
      dockerfile: bun.dockerfile
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: '1G'
    networks:
      - network_application
    ports:
      - '${APP_PORT}:3000/tcp'
    volumes:
      - 'volume_application:${APP_VLM}'
    stdin_open: true
    tty: true
    restart: always
    image: image_application
    container_name: container_application
  service_postgres:
    image: postgres
    container_name: container_postgres
    restart: always
    stdin_open: true
    tty: true
    networks:
      - network_application
    ports:
      - '${PG_PORT}:5432/tcp'
    volumes:
      - volume_postgres:${PG_VLM}
    environment:
      POSTGRES_USER: ${PG_USR}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
